# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    task.manager:
         class: AppBundle\Entity\Manager\TaskManager
         arguments:
            - "@debug.event_dispatcher"

    task_created.listener:
        class: AppBundle\EventListener\TaskCreatedListener
        arguments:
            - "@debug.event_dispatcher"
        tags:
            - { name: kernel.event_listener, event: 'task.created', method: 'onTaskCreated' }